# Generated by Django 5.1.1 on 2025-01-03 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stall', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stall', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('logo', models.ImageField(blank=True, upload_to='stall_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('ubtransact_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='No description provided', max_length=255)),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_password', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='reports/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stall_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_data', to='myApps.stall')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('category', models.CharField(max_length=255)),
                ('unit_of_measurement', models.CharField(max_length=50, verbose_name='Unit of Measurement')),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_quantity', models.IntegerField(verbose_name='Stock Quantity')),
                ('reorder_level', models.IntegerField(verbose_name='Reorder Level')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Batch Number')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('arrival_date', models.DateField(verbose_name='Arrival/Delivery Date')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('stall_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApps.stall')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('stall_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApps.stall')),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(default='Unknown Supplier', max_length=255)),
                ('contact_person', models.CharField(default='Not Provided', max_length=255, verbose_name='Contact Person')),
                ('contact_info', models.CharField(default='Not Provided', max_length=255, verbose_name='Contact Information')),
                ('address', models.TextField(default='Not Provided')),
                ('payment_terms', models.TextField(default='Not Provided')),
                ('tax_information', models.CharField(default='Not Provided', max_length=255, verbose_name='Tax Information')),
                ('license_number', models.CharField(default='Not Provided', max_length=255, verbose_name='License Number')),
                ('contract_start_date', models.DateField(default='2024-01-01', verbose_name='Contract Start Date')),
                ('contract_end_date', models.DateField(default='2025-01-01', verbose_name='Contract End Date')),
                ('stall_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='myApps.stall')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('supplier_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('lead_time', models.IntegerField(verbose_name='Lead Time (days)')),
                ('minimum_order_quantity', models.IntegerField(verbose_name='Minimum Order Quantity')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Unit')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApps.fooditem', verbose_name='Food Item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApps.suplier', verbose_name='Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiration', models.DateTimeField(blank=True, null=True)),
                ('stall_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApps.stall')),
            ],
            options={
                'unique_together': {('firstname', 'lastname')},
            },
        ),
    ]
