# Generated by Django 5.1.1 on 2025-01-06 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApps.stall'),
        ),
    ]
