# Generated by Django 5.1.1 on 2025-01-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApps', '0002_transaction_stall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='stall',
            new_name='stall_name',
        ),
    ]
