# Generated by Django 5.1.1 on 2025-01-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApps', '0003_rename_stall_transaction_stall_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
