# Generated by Django 5.1.1 on 2025-01-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApps', '0004_alter_employee_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='otp_expiration',
        ),
    ]
