# Generated by Django 5.1.1 on 2025-01-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApps', '0006_report_stall_name'),
    ]

    operations = [

    ]
