# Generated by Django 5.1.1 on 2025-01-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApps', '0010_remove_product_description_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_ons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='size_prices',
            field=models.JSONField(default=dict),
        ),
    ]
