# Generated by Django 5.1.1 on 2025-01-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApps', '0011_remove_product_description_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_name',
            field=models.ForeignKey(db_column='item_name_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='myApps.fooditem'),
        ),
    ]
