# Generated by Django 5.1.1 on 2025-01-11 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApps', '0012_remove_product_description_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieritem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
    ]
