# Generated by Django 5.1.4 on 2025-01-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApps', '0013_remove_product_description_remove_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
