from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('employee/', views.employee, name='employee'),
    path('log_in/', views.log_in, name='log_in'),
    path('monthly_total_sales/', views.monthly_total_sales, name='monthly_total_sales'),
    path('yummy_mango/', views.yummy_mango, name='yummy_mango'),
    path('cravers_haven/', views.cravers_haven, name='cravers_haven'),
    path('uncle_brew/', views.uncle_brew, name='uncle_brew'),
    path('sealog_bbq/', views.sealog_bbq, name='sealog_bbq'),
    path('bja_lechon/', views.bja_lechon, name='bja_lechon'),
    path('tusok_tusok/', views.tusok_tusok, name='tusok_tusok'),
    path('process_order/', views.process_order, name='process_order'),
    path('save-transaction/', views.save_transaction, name='save_transaction'),
    path('transaction/', views.transactions_view, name='transaction'),
    path('cravers/', views.cravers, name='cravers'),
    path('uncle/', views.uncle, name='uncle'),
    path('sealog/', views.sealog, name='sealog'),
    path('lechon/', views.lechon, name='lechon'),
    path('tusok/', views.tusok, name='tusok'),
    path('clear_transaction/', views.clear_transaction, name='clear_transaction'),
    path('admin_graph/', views.graph, name='admin_graph'),
    path('inventory/', views.inventory, name='inventory'),
    path('view_item/', views.view_item, name='view_item'),
    path('view_supplier', views.view_supplier, name='view_supplier'),
    path('save_item/', views.save_item, name='save_item'),
    path('update_supplier/<int:id>', views.update_supplier, name='update_supplier'),
    path('delete_supplier/<int:id>/', views.delete_supplier, name='delete_supplier'),
    path('update_item/<int:id>', views.update_item, name='update_item'),
    path('delete_item/<int:id>/', views.delete_item, name='delete_item'),
    path('employee/create/', views.employee_create, name='employee_create'),
    path('emp_records/', views.employees, name='emp_records'),
    path('employee/update/<int:emp_id>/', views.update_employee, name='update_employee'),
    path('employee/delete/<int:id>/', views.delete_employee, name='delete_employee'),
    path('emp_success/', views.emp_success, name='emp_success'),
    path('sales-data/', views.sales_data, name='sales_data'),
    path('super/', views.superadmin_dashboard, name='super'),
    path('supreg/', views.supreg, name='supreg'),
    path('adminrec/', views.adminrec, name='adminrec'),
    path('adminrec/edit/<int:admin_id>/', views.edit_admin, name='edit_admin'),
    path('adminrec/delete/<int:admin_id>/', views.delete_admin, name='delete_admin'),
    path('report/', views.report, name='report'),
    path('reports/', views.report_list, name='report_list'),
    path('user/', views.user, name='user'),
    path('about/', views.about, name='about'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)