# Generated by Django 5.1.1 on 2024-10-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('stall_name', models.CharField(max_length=100)),
            ],
        ),
    ]
