# Generated by Django 5.1.1 on 2024-10-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApps', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='stall_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
